kind: pipeline
type: docker
name: default
steps:
    - name: build
      image: golang
      commands:
        - "cd ./server/cmd"
        - "go build ./..."
    - name: test
      image: golang
      commands:
        - "cd ./server"
        - "go run ./cmd/main.go&"
        - "go test ./... -v"

